
export enum NotificationsType {
  CONNECTION_REQUEST,
  CONNECTION_ACCEPTED,
  NEW_CONNECTION,
  QR_SCANNED,
  NEW_MESSAGE,  
  NEW_CHAT_MESSAGE,
  APPOINTMENT_BOOKED,
  APPOINTMENT_CONFIRMED,
  APPOINTMENT_REMINDER,
  APPOINTMENT_CANCELLED,
  PAYMENT_COMPLETED,
  PRESCRIPTION_RENEWAL_REQUEST,
  PRESCRIPTION_EXPIRY_WARNING,
  NEW_PRESCRIPTION
}
