export enum userStatusInfo {
  INIT = 'INIT',
  PENDING_EMAIL_VERIFICATION = 'PENDING_EMAIL_VERIFICATION',
  EMAIL_VERIFIED = 'EMAIL_VERIFIED',
  PENDING_ADMIN_APPROVAL = 'PENDING_ADMIN_APPROVAL',
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  SUSPENDED = 'SUSPENDED',
}
